name: SwiftQuiz
options:
  bundleIdPrefix: com.nickhart
  createIntermediateGroups: true
  defaultConfig: Release
  xcodeVersion: "15.0"

settings:
  base:
    SWIFT_VERSION: 5.10
    IPHONEOS_DEPLOYMENT_TARGET: 17.0
    MACOSX_DEPLOYMENT_TARGET: 14.0
    MARKETING_VERSION: 1.0
    CURRENT_PROJECT_VERSION: 1
    ENABLE_USER_SCRIPT_SANDBOXING: YES
    DEAD_CODE_STRIPPING: YES
    ASSETCATALOG_COMPILER_GENERATE_SWIFT_ASSET_SYMBOL_EXTENSIONS: YES

targets:
  SwiftQuiz:
    type: application
    platform: iOS
    sources:
      - SwiftQuiz/App/
      - SwiftQuiz/Extensions/
      - SwiftQuiz/Model/
      - SwiftQuiz/Services/
      - SwiftQuiz/Views/
      - SwiftQuiz/ViewModels/
      - SwiftQuiz/Resources
    info:
      path: SwiftQuiz/Resources/Info.plist
      properties:
        CFBundleName: SwiftQuiz
        CFBundleDisplayName: SwiftQuiz
        CFBundleIdentifier: com.nickhart.SwiftQuiz
        CFBundleVersion: $(CURRENT_PROJECT_VERSION)
        CFBundleShortVersionString: $(MARKETING_VERSION)
        LSRequiresIPhoneOS: true
        UILaunchScreen:
          UIColorName: ""
          UIImageName: ""
        UISupportedInterfaceOrientations:
          - UIInterfaceOrientationPortrait
          - UIInterfaceOrientationLandscapeLeft
          - UIInterfaceOrientationLandscapeRight
        UISupportedInterfaceOrientations~ipad:
          - UIInterfaceOrientationPortrait
          - UIInterfaceOrientationPortraitUpsideDown
          - UIInterfaceOrientationLandscapeLeft
          - UIInterfaceOrientationLandscapeRight
        UIBackgroundModes:
          - remote-notification
    entitlements:
      path: SwiftQuiz/Resources/SwiftQuiz.entitlements
    settings:
      base:
        CODE_SIGN_IDENTITY: "Apple Development"
        DEVELOPMENT_TEAM: QCZTZM228N
        PRODUCT_BUNDLE_IDENTIFIER: com.nickhart.SwiftQuiz
        ENABLE_PREVIEWS: true
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: AccentColor

  SwiftQuizMac:
    type: application
    platform: macOS
    sources:
      - SwiftQuiz/App/
      - SwiftQuiz/Model/
      - SwiftQuiz/Services/
      - SwiftQuiz/Views/
      - SwiftQuiz/ViewModels/
      - SwiftQuiz/Resources
    info:
      path: SwiftQuiz/Resources/Info.plist
      properties:
        CFBundleName: SwiftQuiz
        CFBundleDisplayName: SwiftQuiz
        CFBundleIdentifier: com.nickhart.SwiftQuiz
        CFBundleVersion: $(CURRENT_PROJECT_VERSION)
        CFBundleShortVersionString: $(MARKETING_VERSION)
        LSMinimumSystemVersion: "14.0"
    entitlements:
      path: SwiftQuiz/Resources/SwiftQuizMac.entitlements
    settings:
      base:
        CODE_SIGN_IDENTITY: "Apple Development"
        DEVELOPMENT_TEAM: QCZTZM228N
        PRODUCT_BUNDLE_IDENTIFIER: com.nickhart.SwiftQuiz
        ENABLE_PREVIEWS: true
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: AccentColor

  SwiftQuizTests:
    type: bundle.unit-test
    platform: iOS
    sources:
      - SwiftQuizTests/
    dependencies:
      - target: SwiftQuiz
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.nickhart.SwiftQuizTests
        GENERATE_INFOPLIST_FILE: YES
        BUNDLE_LOADER: $(TEST_HOST)
        TEST_HOST: $(BUILT_PRODUCTS_DIR)/SwiftQuiz.app/$(BUNDLE_EXECUTABLE_FOLDER_PATH)/SwiftQuiz

  SwiftQuizUITests:
    type: bundle.ui-testing
    platform: iOS
    sources:
      - SwiftQuizUITests/
    dependencies:
      - target: SwiftQuiz
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.nickhart.SwiftQuizUITests
        GENERATE_INFOPLIST_FILE: YES
        TEST_TARGET_NAME: SwiftQuiz

schemes:
  SwiftQuiz:
    build:
      targets:
        SwiftQuiz: all
        SwiftQuizTests: [test]
        SwiftQuizUITests: [test]
    run:
      config: Debug
    test:
      config: Debug
      targets:
        - SwiftQuizTests
        - SwiftQuizUITests
    archive:
      config: Release

  SwiftQuizMac:
    build:
      targets:
        SwiftQuizMac: all
    run:
      config: Debug
    archive:
      config: Release
